#!/usr/bin/bash
set -e -u

if ${KLOINK_ECHO_REPO_PSW_AND_EXIT:-false}; then
    echo ${KLOINK_REPO_PSW}
    exit 0
fi


INFO=true
VERBOSE=false
function info()    { ${INFO-true} && echo "$*" || true; }
function verbose() { ${VERBOSE-false} && echo "$*" || true; }


# load default settings from config file if exists
# TODO: provide
KLOINK_CONFIG_FILE=~/.config/kloink/kloink.conf
if [[ -f ${KLOINK_CONFIG_FILE} ]]; then
    source ${KLOINK_CONFIG_FILE}
fi

# use default values, unless vars are already defined
: ${KLOINK_DIR:=${KLOINK_DEFAULT_DIR:-~/.cache/kloink}}
: ${KLOINK_BASE_REPO:=${KLOINK_DEFAULT_BASE_REPO:-unknown}}
: ${KLOINK_VERBOSITY:=}
#: ${KLOINK_PATH:=$KLOINK_DIR}


main() {
    while [[ ${1:-} == -* ]]; do
        arg=$1
        case $1 in
            -h|--help)
                show_help
                exit 0
                ;;
            -v|--verbose)
                KLOINK_VERBOSITY=-v
                VERBOSE=true
                ;;
            -q|--quiet)
                KLOINK_VERBOSITY=-q
                INFO=false
                ;;
            -c|--config)
                KLOINK_CONFIG_FILE=$2
                shift
                ;;
            -d|--dir)
                KLOINK_DIR=$2
                shift
                ;;
            #-p|--path)
            #    KLOINK_PATH=$2 # TODO: not used
            #    shift
            #    ;;
            *)  # Default case: No more options, so break out of the loop.
                echo unknown option $1
                show_help
                exit 1
                ;;
        esac
        shift
    done
    local cmd=${1:-help}
    shift
    case $cmd in
        help)
            show_help
            exit 0
            ;;
        klone)
            kloink_klone "${@}"
            ;;
        link)
            kloink_link "${@}"
            ;;
        s|status)
            kloink_dirs "git status --short" "${@}"
            ;;
        pull)
            kloink_dirs "git pull $KLOINK_VERBOSITY"  "${@}"
            ;;
        push)
            kloink_dirs "git push $KLOINK_VERBOSITY"  "${@}"
            ;;
        git)
            echo git subcommand not implemented yet
            exit 1
            ;;
        cmd)
            echo cmd subcommand not implemented yet
            exit 1
            # TODO CMD=any_command
            any="$1 || true"
            ;;
        *)
            echo unknown subcommand $CMD
            show_help
            exit 1
    esac
}

klone_find_in_path() {
    NAME=$1
    VERSION=$2
    # First search in the path, and finally search in the KLOINK_DIR
    # The KLOINK_DIR maybe first in the path as well, but it needs to be searched at least once
    # because that is where it will be kloned if not found
    for dir in ${KLOINK_PATH//:/ } ${KLOINK_DIR}; do
        if [[ -d $dir/$NAME-$VERSION ]]; then
            echo $dir/$NAME-$VERSION
            return
        fi
    done
}

kloink_link() {
    if (($# < 2 || $# > 3 )); then
        echo '2 or 3 arguments needed: [path/]<name> <version> [repo-url]'
        show_help
        exit 1
    fi
    local path=$1
    local version=$2
    local name=${path##*/}
    local dir=$KLOINK_DIR/$name-$version

    kloink_klone "${@}"  # make sure the klone exists
    if [[ -h $path ]]; then
        echo updating link $path to $dir
        rm $path # somehow the NAME --force does not seem to work
        ln --force -s $dir $path
    elif [[ -e $path ]]; then
        echo ERROR: $name already exists, but is not a symbolic link
        exit 1
    else
        echo creating link $path to $dir
        ln -s $dir $path
    fi
}

kloink_klone() {
    if (($# < 2 || $# > 3 )); then
        echo '2 or 3 arguments needed: [path/]<name> <version> [repo-url]'
        show_help
        exit 1
    fi
    local path=$1
    local version=$2
    local repo=${3:-}
    local name=${path##*/}  # ignore preceding path to also work with same arguments as link
    local dir=$KLOINK_DIR/$name-$version
    if [[ -d $dir ]]; then
        _check_klone $dir $version
    elif [[ ! -e $dir ]]; then
        if [[ -z $repo ]]; then
            repo=${KLOINK_BASE_REPO}/${name}.git
        fi
        if [[ -z ${KLOINK_REPO_PSW:-} ]]; then
            # this is hack so that this kloink program itself can be used for GIT_ASKPASS
            # if the setting below is true, running kloink will just echo the password
            export KLOINK_ECHO_REPO_PSW_AND_EXIT=true
            export GIT_ASKPASS=${BASH_SOURCE[0]}
        fi
        #CLONE_OPTS="--depth 1"
        git clone  -c advice.detachedHead=false --branch=$version -- $repo $dir
        unset KLOINK_ECHO_REPO_PSW_AND_EXIT
    else
        echo $dir already exist but is not a correct clone
        exit 1
    fi
}

_check_klone() {
    local dir=$1
    local version=$2
    if [[ -d $dir ]]; then
        echo $dir already exists, checking if version is $version
        cur_version=$(kloink_git_version $dir)
        if [[ $version != $cur_version ]]; then
            echo Current dir $dir is on version $cur_version, please remove this first
            exit 1
        fi
    elif [[ -e $dir ]]; then
        echo ERROR: $dir already exists, but is not a directory
        exit 1
    fi
}

kloink_git_version() {
    local OLD_DIR=`pwd`
    cd $1
    git symbolic-ref -q --short HEAD || git describe --tags --exact-match
    cd $OLD_DIR
}

kloink_dirs() {
    local cmd=$1
    shift
    local main_dir=`pwd`
    local dir
    for dir in "${@}"; do
        app=${dir%.deploy*}
        if [[ -d $dir/.git ]]; then
            info ======= $dir =============
            cd $dir
            $cmd
            cd $main_dir
        else
            verbose Skipping $dir
        fi
    done
}

show_help() {
    # show help while stripping of MarkDown ** bold markup
    sed -e 's/*//g' << EOF
Usage:
  ${0##*/} [options] klone <name> <version> [repo-url]
  ${0##*/} [options] link  [path/]<name> <version> [repo-url]
  ${0##*/} [options] status [dir ...]
  ${0##*/} [options] pull [dir ...]
  ${0##*/} [options] push [dir ...]
  ${0##*/} [options] git <subcommand> [args] [-- [dir ...]] (TODO)
  ${0##*/} [options] cmd <command> [args] [-- [dir ...]]    (TODO)

kloink manages a set of git clones of a repository to use s specific version (tags/branches)
of the same repo.

Options can be:
       --help           show this help
    -d|--dir <dir>      the directory where new clones are stored. see KLOINK_DIR (default: ~/.cache/kloink)
    -t|--target <dir>   the target directory where to make the link. see KLOINK_TARGET (default .)
    -p|--path <dirs>    a colon separated list of dirs to search for clones. see KLOINK_PATH
EOF
}


 klone_ssh() {
    local name=$1
    local version=$2
    local dir=$3
    local repo=${KLOINK_SSH_REPO}/${name}.git
    git clone  -c advice.detachedHead=false --branch=$version -- $repo $dir
}

 klone_https() {
    local name=$1
    local version=$2
    local dir=$3
    REPO=${KLOINK_HTTPS_REPO}/${NAME}.git
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    export GIT_ASKPASS=${SCRIPT_DIR}/echo-kloink-repo-psw.sh
    #CLONE_OPTS="--depth 1"
    git clone  -c advice.detachedHead=false --branch=$VERSION -- $REPO $DIR
}



main "${@}"
